#:schema https://yazi-rs.github.io/schemas/yazi.json

[opener]
inkscape = [{ run = "inkscape %s", orphan = true, desc = "Inkscape" }]
less = [{ run = "less %s", block = true, desc = "less" }]
mimeopen = [
    { run = "mimeopen --ask %s", block = true, desc = "Open with mime-associated softwares" },
]
thunar = [{ run = "thunar %s", desc = "Reveal with thunar", for = "linux" }]

[open]
prepend_rules = [
    { mime = "image/svg+xml", use = [
        "open",
        "inkscape",
        "edit",
        "reveal",
    ] },
    { mime = "text/html", use = [
        "open",
        "edit",
        "reveal",
    ] },
    { mime = "text/plain", use = [
        "edit",
        "reveal",
        "less",
    ] },
    { mime = "*", use = [
        "open",
        "reveal",
        "thunar",
        "mimeopen",
    ] },
]

[[plugin.prepend_fetchers]]
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
url = "*/"
run = "git"
group = "git"
